name: NodeJs

on:
  workflow_dispatch:

jobs:
  node-build-test-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
  
    - name: Cache Packages
      uses: actions/cache@v2
      with:
        path: |
          ui/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

    - name: Npm Dependencies
      run: |
        npm install
    
    - name: Npm test
      run:
        npm run test-headless

    - name: Package 
      run: |
        docker build -t npm-project:latest .
        
